apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-name" . }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    cloud.google.com/backend-config: '{"default": {{ include "gke-backend-config-name" . | quote }}}'
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}